SwiftSearch/Controllers/FurnituresController.cs
using SwiftSearch.Data;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList;
using SwiftSearch.Interfaces;
using System.Web.Helpers;
using SwiftSearch.RemitaResources.Infrastructure;

namespace SwiftSearch.Controllers
{
    public class FurnituresController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IFurnitureRepository _furnitureRepository;

        private IGateWayIntegrator Integrator { get; set; }
        private IntegrateConfig config;
        private RemitaHashGenerator _hasher;

        public FurnituresController(IUnitOfWork unitOfWork, IFurnitureRepository furnitureRepository)
        {
            #region RemitaConfig
            //demo credentails provided by remita for use in development.
            //substitute with actual live credentials.
            config = new SampleConfig("2547916", "4430731", "1946");
            _hasher = new RemitaHashGenerator(config);
            //Better way would be to use DI to inject everything rather than newing up thing in the controller
            Integrator = new RemitaGateWayIntegrator(_hasher); 
            #endregion

           
            _unitOfWork = unitOfWork;
            _furnitureRepository = furnitureRepository; 
        }
        // GET: Furnitures
        public async Task<ActionResult> Index()
        {
            var list = await _furnitureRepository.GetAllDataAsync();
            return View(list);
        }
        public ActionResult Listing(string sortOn, string orderBy, string pSortOn, int? page)
        {
            int recordsPerPage = 3;
            if (!page.HasValue)
            {
                page = 1; // set initial page value
                if (string.IsNullOrWhiteSpace(orderBy) || orderBy.Equals("asc"))
                {
                    orderBy = "desc";
                }
                else
                {
                    orderBy = "asc";
                }
            }



            ViewBag.OrderBy = orderBy;
            ViewBag.SortOn = sortOn;
           
            var list = _furnitureRepository.GetFurnituresBySearch().ToList();
            
            var finalList = list.ToPagedList(page.Value, recordsPerPage);
            
            return View(finalList);
        }
        // GET: Furnitures/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var detail = await _furnitureRepository.FindAsync(id);
            return View(detail);
        }

        // GET: Furnitures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Furnitures/Create
        [HttpPost]
        public ActionResult Create(Furniture furniture)
        {

                if (ModelState.IsValid)
                {

                    var fileName = Path.GetFileNameWithoutExtension(furniture.ImageFile.FileName);
                    var extension = Path.GetExtension(furniture.ImageFile.FileName);
                    fileName = fileName + Guid.NewGuid().ToString() + extension;
                    furniture.FurnitureImage = "~/PhotoUploads/Furnitures/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/PhotoUploads/Furnitures/"), fileName);
                    furniture.ImageFile.SaveAs(fileName);
                    //resizing image
                    MemoryStream ms = new MemoryStream();
                    WebImage webImage = new WebImage(fileName);
                    if (webImage.Width > 700)
                    {
                        webImage.Resize(700, 564, false);
                        webImage.Save(fileName);
                    }
                    _furnitureRepository.Insert(furniture);
                    _unitOfWork.Complete();
                    return RedirectToAction("Index");
                }
           
            return View(furniture);
        }

        // GET: Furnitures/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var edit = await _furnitureRepository.FindAsync(id);
            return View(edit);
        }

        // POST: Furnitures/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Furniture furniture)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {

                    var fileName = Path.GetFileNameWithoutExtension(furniture.ImageFile.FileName);
                    var extension = Path.GetExtension(furniture.ImageFile.FileName);
                    fileName = fileName + Guid.NewGuid().ToString() + extension;
                    furniture.FurnitureImage = "~/PhotoUploads/Vehicles/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/PhotoUploads/Vehicles/"), fileName);
                    furniture.ImageFile.SaveAs(fileName);
                    //resizing image
                    MemoryStream ms = new MemoryStream();
                    WebImage webImage = new WebImage(fileName);
                    if (webImage.Width > 700)
                    {
                        webImage.Resize(700, 564, false);
                        webImage.Save(fileName);
                    }
                    _furnitureRepository.Update(furniture);
                    _unitOfWork.Complete();
                    return RedirectToAction("Index");
                }
               
            }
            catch
            {
                throw new ArgumentNullException(String.Format($"Cannot Update {furniture.FurnitureName} "));
            }
            return View(furniture);
        }

        // GET: Furnitures/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var delete = await _furnitureRepository.FindAsync(id);

            return View(delete);
        }

        // POST: Furnitures/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, Furniture furniture)
        {
            try
            {
                // TODO: Add delete logic here
                _furnitureRepository.FindAsync(id);
                _furnitureRepository.Delete(furniture);
                return RedirectToAction("Index");
            }
            catch
            {
                throw new ArgumentException(String.Format($"The {furniture.FurnitureName} could not be deleted"));
            }
           // return View();
        }
    }
}

SwiftSearch/Controllers/HomeController.cs
using PagedList;
using SwiftSearch.Data;
using SwiftSearch.Helpers;
using SwiftSearch.Interfaces;
using SwiftSearch.Models;
using SwiftSearch.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwiftSearch.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IVehicleRepository _vehicleRepository;
        private readonly IFurnitureRepository _furnitureRepository;

        public HomeController(IUnitOfWork unitOfWork,IVehicleRepository vehicleRepository,IFurnitureRepository furnitureRepository)
        {
            _unitOfWork = unitOfWork;
            _vehicleRepository = vehicleRepository;
            _furnitureRepository = furnitureRepository;
        }
        

        public ActionResult Index(string sortOn, string orderBy,string pSortOn, string keyword, int? page)
        {
          
            int recordsPerPage = 3;
            if (!page.HasValue)
            {
                page = 1; // set initial page value
                if (string.IsNullOrWhiteSpace(orderBy) || orderBy.Equals("asc"))
                {
                    orderBy = "desc";
                }
                else
                {
                    orderBy = "asc";
                }
            }

            ViewBag.OrderBy = orderBy;
            ViewBag.SortOn = sortOn;
            ViewBag.Keyword = keyword;

            var list = _vehicleRepository.GetVehiclesBySearch();
            var list2 = _furnitureRepository.GetFurnituresBySearch();
 
            if (!string.IsNullOrWhiteSpace(keyword))
            {
              
                list = list.Where(
                                  f => f.CarName.ToLower().Contains(keyword.ToLower()) ||
                                  f.CarModel.ToLower().Contains(keyword.ToLower()) ||
                                  f.CarDealer.ToLower().Contains(keyword.ToLower()) ||
                                  f.CarPrice.ToString().ToLower().Contains(keyword.ToLower()) ||
                                  f.CarAddress.ToLower().Contains(keyword.ToLower()) ||
                                  f.CarColor.ToLower().Contains(keyword.ToLower())
                                  );
                list2 = list2.Where(
                                    f => f.FurnitureName.ToLower().Contains(keyword.ToLower()) ||
                                    f.FurnitureModel.ToLower().Contains(keyword.ToLower()) ||
                                    f.FurnitureDealer.ToLower().Contains(keyword.ToLower()) ||
                                    f.FurniturePrice.ToString().ToLower().Contains(keyword.ToLower()) ||
                                    f.FurnitureAddress.ToLower().Contains(keyword.ToLower()) ||
                                    f.FurnitureColor.ToLower().Contains(keyword.ToLower())
                                    );
            }
           if(!list.Any() || !list2.Any())
            {
                var error = "No Item(s) Matches your Search";
                ViewBag.Error = error;
            }
            var finalList = list.ToPagedList(page.Value, recordsPerPage);
            var finalList1 = list2.ToPagedList(page.Value, recordsPerPage);

            var flist = new Tuple<IPagedList<Vehicle>, IPagedList<Furniture>>(finalList, finalList1);
           
            return View(flist);
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SwiftSearch/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SwiftSearch/Views/Home/Categories.cshtml
@model IEnumerable<SwiftSearch.Helpers.Category>
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categories</h2>

@using (Html.BeginForm())
{
<div>
    @Html.DropDownList("Category", ViewBag.Category as SelectList, htmlAttributes: new { @class = "form-control" })
</div>
<div>
    <input type="submit" value="Submit" class="btn btn-primary submit" />
</div>

    
}

SwiftSearch/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SwiftSearch/Views/Home/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model Tuple<IPagedList<SwiftSearch.Data.Vehicle>, IPagedList<SwiftSearch.Data.Furniture>>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


    <div class="search-form-header no-overlap">
        <div class="container">
            <h2 class="text-center ">Get all Your Cars and Furnitures here on the go!</h2>

                @using (Html.BeginForm())
        {

            <div class="row search-form-top-fields">
                <div class="col-md-11">
                    <input type="text" name="keyword" value="@ViewBag.Keyword" placeholder="Enter your Cars and Furniture names and Manufactures here, e.g.: Toyota, Sofa, Mercerdes, Honda, etc" class="form-control" />
                </div>

                <div class="col-md-1">
                    <button type="submit" class="form-btn search-btn"><i class="ion-android-search"></i></button>
                </div>
            </div>
}


            </div>
        </div>

    <main id="main" class="main">


        <div class="container row-padding">
            <div class="row">
                <div class="col-md-8">
                    <header class="section-header">

                        <h2 class="section-title">Popular Listings</h2>
                    </header>
                </div>
                <div class="col-md-4 text-right">
                    <br>
                    <br>
                    <a href="property-grid.html" class="btn btn-outline-primary">More Properties</a>
                </div>
            </div>
        
            <div class="row">
                @if (Model == null)
             {
                <h3 class="text-danger">@ViewBag.Error</h3>
            }
            else
            {
foreach (var item in Model.Item1)
{
            <div class="col-md-6 col-lg-4">
                <article class="property-post property-post-grid clearfix">
                    <div class="property-thumbnail">
                        <a href="@Url.Action("Details","Vehicles", new { id=item.ID})"><img src="@Url.Content(item.CarImage)" alt="Property"></a>
                        <div class="property-label"><a href="#">For Sale</a></div>
                    </div>
                    <div class="property-wrap">
                        <header class="property-header clearfix">
                            <div class="property-actions-wrap">
                                <span class="action-btn property-gallery-images" data-toggle="tooltip" data-placement="top" title="3 Photos"><i class="fa fa-camera"></i></span>
                                <span class="action-btn property-add-to-fav" data-toggle="tooltip" data-placement="top" title="Add to Favorite"><i class="fa fa-heart"></i></span>
                                <span class="action-btn property-add-to-compare" data-property-id="12" data-toggle="tooltip" data-placement="top" title="Add to Compare"><i class="fa fa-exchange"></i></span>
                            </div>
                            <h2 class="property-title">
                                <a href="single-property.html">@item.CarName</a>
                            </h2>
                            <p class="property-location">@item.CarAddress</p>

                        </header>
                        <ul class="property-meta list-unstyled">
                            <li>@item.CarModel</li>

                        </ul>
                        <footer class="property-footer">
                            <div class="row">
                                <div class="col-6">
                                    <span class="property-price"><span>#</span>@item.CarPrice.ToString("#,##,00.00")</span>
                                </div>
                                <div class="col-6 text-right">
                                    <a href="@Url.Action("Details","Vehicles", new { id = item.ID})" class="btn btn-primary">More Info</a>
                                </div>
                            </div>
                        </footer>
                    </div>
                </article>
            </div>
}
foreach (var item in Model.Item2)
{
            <div class="col-md-6 col-lg-4">
                <article class="property-post property-post-grid clearfix">
                    <div class="property-thumbnail">
                        <a href="@Url.Action("Details","Vehicles", new { id=item.ID})"><img src="@Url.Content(item.FurnitureImage)" alt="Property"></a>
                        <div class="property-label"><a href="#">For Sale</a></div>
                    </div>
                    <div class="property-wrap">
                        <header class="property-header clearfix">
                            <div class="property-actions-wrap">
                                <span class="action-btn property-gallery-images" data-toggle="tooltip" data-placement="top" title="3 Photos"><i class="fa fa-camera"></i></span>
                                <span class="action-btn property-add-to-fav" data-toggle="tooltip" data-placement="top" title="Add to Favorite"><i class="fa fa-heart"></i></span>
                                <span class="action-btn property-add-to-compare" data-property-id="12" data-toggle="tooltip" data-placement="top" title="Add to Compare"><i class="fa fa-exchange"></i></span>
                            </div>
                            <h2 class="property-title">
                                <a href="single-property.html">@item.FurnitureName</a>
                            </h2>
                            <p class="property-location">@item.FurnitureAddress</p>

                        </header>
                        <ul class="property-meta list-unstyled">
                            <li>@item.FurnitureModel</li>

                        </ul>
                        <footer class="property-footer">
                            <div class="row">
                                <div class="col-6">
                                    <span class="property-price"><span>#</span>@item.FurniturePrice.ToString("#,##,00.00")</span>
                                </div>
                                <div class="col-6 text-right">
                                    <a href="@Url.Action("Details","Furnitures", new { id = item.ID})" class="btn btn-primary">More Info</a>
                                </div>
                            </div>
                        </footer>
                    </div>
                </article>
            </div>
}
}

            </div>
        </div>


    </main>

    <div class="pagedList" style="margin:5%">
        @Html.PagedListPager((Model.Item1), page => Url.Action("Index", new
        {
            page,
            sortOn = ViewBag.SortOn,
            orderBy = ViewBag.OrderBy,
            pSortOn = ViewBag.SortOn,
            keyword = ViewBag.Keyword
        }),
                 PagedListRenderOptions.ClassicPlusFirstAndLast)
    </div>

SwiftSearch/Views/Home/Index1.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>